[package]
name = "akkhara"
version = "0.3.8"
edition = "2021"

[[bin]]
name = "akk"
path = "src/main.rs"

[dependencies]
rand = "0.8"
ureq = { version = "2.9", default-features = false, features = ["native-tls", "gzip"] }
native-tls = { version = "0.2", features = ["vendored"] }
crossterm = "0.27"

[profile.release]
opt-level = 3
